# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='depart',
            field=models.CharField(choices=[('coe', 'COE'), ('mdm', 'MDM'), ('edm', 'EDM')], default='coe', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume', verbose_name='Teacher Resume'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(to='profiles.Course'),
        ),
    ]
